### ISSUE TITLE
Loading is true only once?

### ISSUE THREAD

**Issue by theshire-io** [sonaye/mobx-apollo#21]
`loading` does not seem to ever become `true` again with `refrechQueries`:

![image](https://user-images.githubusercontent.com/44207553/49687277-6904cd80-fb09-11e8-887c-64e65ca37073.png)

```
  @computed
  get rulesRaw() {
    if (!this.rootStore || !this.rootStore.graphqlClient) {
      return;
    }

    return graphql({
      client: this.rootStore.graphqlClient,
      query: queries.fetchRules,
    });
  }

  @computed get loading() {
    return this.rulesRaw.loading;
  }

  @computed get rules() {
    return pathOr([], ['data', 'rule'], this.rulesRaw);
  }

  // Similarly for the other crud actions
  @action.bound
  deleteRule(id) {
    return this.rootStore.graphqlClient.mutate({
      mutation: mutations.removeRule,
      variables: {id},
      refetchQueries: [{query: queries.fetchRules}],
      awaitRefetchQueries: true,
    });
  }

```

`rules` get updated fine but `loading` is always `false` after the first run no matter what. 

```
    "apollo-cache-inmemory": "^1.3.11",
    "apollo-client": "^2.4.7",
    "apollo-link": "^1.2.4",
    "apollo-link-http": "^1.5.7",
    "apollo-link-ws": "^1.0.10",
    "apollo-utilities": "^1.0.26",
    "mobx": "^5.5.0",
```

**Comment by sonaye** [comment]
That is the intended behavior, you should add another loading flag for any custom methods you call on top of the ref. The loading indicator you see is meant for the observable itself, which is used internally.

You can try forcing it to be always `true` instead of `value.loading`, not sure if that will give you the result you are after.
https://github.com/sonaye/mobx-apollo/blob/dd1bdaebf2af2ba95e82830e0ea7d5ba050bcd39/src/index.js#L13
