### ISSUE TITLE
How to handle loading?

### ISSUE THREAD

**Issue by pselden** [sonaye/mobx-apollo#8]
Is there a way to get at the "loading" property of a query? Seems like it might be a breaking change because of the way this library returns the prop directly.

**Comment by sonaye** [comment]
The loading prop doesn't behave as you normally would expect because we are not utilizing it with the apollo client directly here. That being said, you can utilize `onFetch` and `onError` to achieve the results you are looking for.

I just pushed new version that makes this even easier, please take a look at the updated example.

**Comment by sonaye** [comment]
Loading prop has been added now in the latest release.
